<a href="https://colab.research.google.com/github/DeepakRautella/google_collab/blob/main/Complete_end_to_end_NLP_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NLP Preprocessing**
Natural language processing (NLP) is the ability of a computer program to understand human language as it is spoken and written -- 
referred to as natural language. It is a component of artificial intelligence (AI).

NLP has existed for more than 50 years and has roots in the field of linguistics. It has a variety of real-world applications in a number of fields, including medical research, search engines and business intelligence.

In [1]:
#python is a case sensitive language, it treats What and what differently so its better to lower case each text or uppercase

In [2]:
import requests
import json
import pandas as pd


In [3]:

raw_data=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=ac54c3cbbf7d6d30db1572077606adda&language=en-US&page=1')

In [4]:
pd.DataFrame(raw_data.json()['results'])

adult                     backdrop_path         genre_ids      id  \
0   False  /rl7Jw8PjhSIjArOlDNv0JQPL1ZV.jpg       [10749, 18]  851644   
1   False  /tmU7GeKVybMWFButWEGl2M4GeiP.jpg          [18, 80]     238   
2   False  /kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg          [18, 80]     278   
3   False  /bxSBOAD8AuMHYMdW3jso9npAkgt.jpg       [10751, 18]  667257   
4   False  /kGzFbGhp99zva6oZODW5atUtnqi.jpg          [18, 80]     240   
5   False  /vI3aUGTuRRdM7J78KIdW98LdxE5.jpg   [35, 18, 10749]   19404   
6   False  /zb6fM1CX41D9rF9hdgclu0peUmy.jpg   [18, 36, 10752]     424   
7   False  /aVFx1VtlOxR3v0ADEatalXOvwbu.jpg      [16, 14, 28]  620249   
8   False  /Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg   [16, 10751, 14]     129   
9   False  /3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg       [10749, 16]  372754   
10  False  /qqHQsStV6exghCM7zbObuYBiYxw.jpg              [18]     389   
11  False  /mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg   [10749, 16, 18]  372058   
12  False   /TU9NIjwzjoKPwQHoHshkFcQUCG.jpg      [35, 53, 18]  496243   
13  False  /l6hQWH9eDksNJNiXWYRkWqikOdu.jpg      [14, 18, 80]     497   
14  False  /nMKdUUepR0i5zn0y1T4CsSB5chy.jpg  [18, 28, 80, 53]     155   
15  False  /jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg           [10749]  724089   
16  False  /w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg           [10749]  696374   
17  False  /aQ7444JX7gefPhGJTlvilj3zG2S.jpg           [10402]  553512   
18  False  /suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg          [53, 80]     680   
19  False  /x4biAVdPVCghBlsVIzB6NmbghIz.jpg              [37]     429   

   original_language                   original_title  \
0                 ko                          20세기 소녀   
1                 en                    The Godfather   
2                 en         The Shawshank Redemption   
3                 es                 Cosas imposibles   
4                 en            The Godfather Part II   
5                 hi     दिलवाले दुल्हनिया ले जायेंगे   
6                 en                 Schindler's List   
7                 zh                            罗小黑战记   
8                 ja                         千と千尋の神隠し   
9                 ja                              同級生   
10                en                     12 Angry Men   
11                ja                            君の名は。   
12                ko                              기생충   
13                en                   The Green Mile   
14                en                  The Dark Knight   
15                en       Gabriel's Inferno: Part II   
16                en                Gabriel's Inferno   
17                ko                   번 더 스테이지: 더 무비   
18                en                     Pulp Fiction   
19                it  Il buono, il brutto, il cattivo   

                                             overview  popularity  \
0   Yeon-du asks her best friend Bora to collect a...     243.993   
1   Spanning the years 1945 to 1955, a chronicle o...     101.202   
2   Framed in the 1940s for the double murder of h...      92.813   
3   Matilde is a woman who, after the death of her...      65.323   
4   In the continuing saga of the Corleone crime f...      50.338   
5   Raj is a rich, carefree, happy-go-lucky second...      28.817   
6   The true story of how businessman Oskar Schind...      72.585   
7   In the bustling human world, spirits live peac...      13.865   
8   A young girl, Chihiro, becomes trapped in a st...      76.852   
9   Rihito Sajo, an honor student with a perfect s...      12.150   
10  The defense and the prosecution have rested an...      35.367   
11  High schoolers Mitsuha and Taki are complete s...      83.041   
12  All unemployed, Ki-taek's family takes peculia...      62.967   
13  A supernatural tale set on death row in a Sout...      73.441   
14  Batman raises the stakes in his war on crime. ...      65.379   
15  Professor Gabriel Emerson finally learns the t...      14.198   
16  An intriguing and sinful exploration of seduct...      13.890   
17  A documentary following th

In [65]:
from IPython.utils import text
#to import from 500 pages
dataset=pd.DataFrame()
for i in range(1,500):
  raw_data=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=ac54c3cbbf7d6d30db1572077606adda&language=en-US&page={}'.format(i))
  temp_df=pd.DataFrame(raw_data.json()['results'])
  dataset=dataset.append(temp_df,ignore_index=True)
  

In [6]:
dataset.head(5)

adult                     backdrop_path    genre_ids      id  \
0  False  /rl7Jw8PjhSIjArOlDNv0JQPL1ZV.jpg  [10749, 18]  851644   
1  False  /tmU7GeKVybMWFButWEGl2M4GeiP.jpg     [18, 80]     238   
2  False  /kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg     [18, 80]     278   
3  False  /bxSBOAD8AuMHYMdW3jso9npAkgt.jpg  [10751, 18]  667257   
4  False  /kGzFbGhp99zva6oZODW5atUtnqi.jpg     [18, 80]     240   

  original_language            original_title  \
0                ko                   20세기 소녀   
1                en             The Godfather   
2                en  The Shawshank Redemption   
3                es          Cosas imposibles   
4                en     The Godfather Part II   

                                            overview  popularity  \
0  Yeon-du asks her best friend Bora to collect a...     243.993   
1  Spanning the years 1945 to 1955, a chronicle o...     101.202   
2  Framed in the 1940s for the double murder of h...      92.813   
3  Matilde is a woman who, after the death of her...      65.323   
4  In the continuing saga of the Corleone crime f...      50.338   

                        poster_path release_date                     title  \
0  /od22ftNnyag0TTxcnJhlsu3aLoU.jpg   2022-10-06         20th Century Girl   
1  /3bhkrj58Vtu7enYsRolD1fZdja1.jpg   1972-03-14             The Godfather   
2  /hBcY0fE9pfXzvVaY4GKarweriG2.jpg   1994-09-23  The Shawshank Redemption   
3  /t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg   2021-06-17         Impossible Things   
4  /hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg   1974-12-20     The Godfather Part II   

   video  vote_average  vote_count  
0  False           8.7         284  
1  False           8.7       16970  
2  False           8.7       22726  
3  False           8.6         293  
4  False           8.6       10284

In [66]:
limited_data=dataset[['original_title','overview','genre_ids']]

In [67]:
limited_data.head(3)

original_title  \
0                   20세기 소녀   
1             The Godfather   
2  The Shawshank Redemption   

                                            overview    genre_ids  
0  Yeon-du asks her best friend Bora to collect a...  [10749, 18]  
1  Spanning the years 1945 to 1955, a chronicle o...     [18, 80]  
2  Framed in the 1940s for the double murder of h...     [18, 80]

**Text Preprocessing**
Data Preprocessing is the most essential step for any Machine Learning model. How well the raw data has been cleaned and preprocessed plays a major role in the performance of the model. Likewise in the case of NLP, the very first step is Text Processing.

The various preprocessing steps that are involved are :

* Lower Casing
* Tokenization
* Punctuation Mark Removal
* Stop Word Removal
* Stemming
* Lemmatization
etc

**Lower Case all text**

In [9]:
limited_data['overview']=limited_data['overview'].str.lower()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [10]:
limited_data['overview']

0       yeon-du asks her best friend bora to collect a...
1       spanning the years 1945 to 1955, a chronicle o...
2       framed in the 1940s for the double murder of h...
3       matilde is a woman who, after the death of her...
4       in the continuing saga of the corleone crime f...
                              ...                        
9975    a crew of miniature aliens operate a spaceship...
9976    200 years after his shocking creation, dr. fra...
9977    amy, an 11-year-old girl, joins a group of dan...
9978    a desperate father tries to return home to his...
9979    parole officer jack mabry has only a few weeks...
Name: overview, Length: 9980, dtype: object

In [11]:
#remove regular expressions
limited_data['overview'][0]

"yeon-du asks her best friend bora to collect all the information she can about baek hyun-jin while she is away in the u.s. for heart surgery. bora decides to get close to baek's best friend, pung woon-ho first. however, bora's clumsy plan unfolds in an unexpected direction. in 1999, a year before the new century, bora, who turns seventeen, falls into the fever of first love."

In [12]:

limited_data['overview'][1]

'spanning the years 1945 to 1955, a chronicle of the fictional italian-american corleone crime family. when organized crime family patriarch, vito corleone barely survives an attempt on his life, his youngest son, michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.'

**Regular expression removal using re **

In [13]:
#if any regular exxpression use re
import re
def remove_html_tags(text):
  pattern=re.compile("<.*?>")
  return pattern.sub(r'',text)


In [14]:
example="<h1> this is a sample for removing html tags </h1><p>dsagdkjashdkjashdkjashdksjahdkjashd</p>"
remove_html_tags(example)

' this is a sample for removing html tags dsagdkjashdkjashdkjashdksjahdkjashd'

**Remove urls**

In [15]:
#remove urls from text data

In [16]:
example="for movie dataset link given as https://api.themoviedb.org/3/movie/top_rated?api_key=<<apikeys>>&language=en-US&page=1"
example1="google site www.google.co.in"
example2="link for non credential sites starts http://sdhaslkdjslakd.sdklaskd/"


In [17]:
def remove_url_tags(text):
  pattern= re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)

In [18]:
remove_url_tags(example)

'for movie dataset link given as '

In [19]:
remove_url_tags(example1)

'google site '

In [20]:
remove_url_tags(example2)

'link for non credential sites starts '

**remove punctuation**

during tokenization it will work as seperate token               #or may be it will attach to others and treat same words different
example : hello hello!

In [21]:
import string,time

In [22]:
exclude=string.punctuation

In [68]:
def remove_punc(text):
  for char in exclude:
    text=text.replace(char,"")
  return text


In [69]:
text="string. hello hello! me? what?"
start=time.time()
print(remove_punc(text))
time1=time.time()-start
print(time1)


string hello hello me what
0.00019598007202148438


In [70]:
#its slow best way is to use 
def remove_punc1(text):
  return text.translate(str.maketrans('','',exclude))

In [71]:
text="string. hello hello! me? what?"
start=time.time()
print(remove_punc1(text))
time1=time.time()-start
print(time1)

string hello hello me what
0.0002079010009765625


In [72]:
limited_data['overview']=limited_data['overview'].apply(remove_punc1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [73]:
limited_data['overview'][1]

'Spanning the years 1945 to 1955 a chronicle of the fictional ItalianAmerican Corleone crime family When organized crime family patriarch Vito Corleone barely survives an attempt on his life his youngest son Michael steps in to take care of the wouldbe killers launching a campaign of bloody revenge'

**Chat words**handling chat short words like rolf,lol,idk, etc

In [75]:
chat_words=requests.get('https://raw.githubusercontent.com/DeepakRautella/sms_slang/main/slang')

In [76]:
chat_words=chat_words.text.split('\n')

In [77]:
chat_words=chat_words[:-1]

In [78]:
chat_words

['AFAIK=As Far As I Know',
 'AFK=Away From Keyboard',
 'ASAP=As Soon As Possible',
 'ATK=At The Keyboard',
 'ATM=At The Moment',
 'A3=Anytime, Anywhere, Anyplace',
 'BAK=Back At Keyboard',
 'BBL=Be Back Later',
 'BBS=Be Back Soon',
 'BFN=Bye For Now',
 'B4N=Bye For Now',
 'BRB=Be Right Back',
 'BRT=Be Right There',
 'BTW=By The Way',
 'B4=Before',
 'B4N=Bye For Now',
 'CU=See You',
 'CUL8R=See You Later',
 'CYA=See You',
 'FAQ=Frequently Asked Questions',
 'FC=Fingers Crossed',
 "FWIW=For What It's Worth",
 'FYI=For Your Information',
 'GAL=Get A Life',
 'GG=Good Game',
 'GN=Good Night',
 'GMTA=Great Minds Think Alike',
 'GR8=Great!',
 'G9=Genius',
 'IC=I See',
 'ICQ=I Seek you (also a chat program)',
 'ILU=ILU: I Love You',
 'IMHO=In My Honest/Humble Opinion',
 'IMO=In My Opinion',
 'IOW=In Other Words',
 'IRL=In Real Life',
 'KISS=Keep It Simple, Stupid',
 'LDR=Long Distance Relationship',
 'LMAO=Laugh My A.. Off',
 'LOL=Laughing Out Loud',
 'LTNS=Long Time No See',
 'L8R=Later',
 'M

In [79]:
chat_words_dict={}
for words in chat_words:
  words=words.split('=')
  chat_words_dict[words[0]]=words[1]

In [80]:
chat_words_dict

{'AFAIK': 'As Far As I Know',
 'AFK': 'Away From Keyboard',
 'ASAP': 'As Soon As Possible',
 'ATK': 'At The Keyboard',
 'ATM': 'At The Moment',
 'A3': 'Anytime, Anywhere, Anyplace',
 'BAK': 'Back At Keyboard',
 'BBL': 'Be Back Later',
 'BBS': 'Be Back Soon',
 'BFN': 'Bye For Now',
 'B4N': 'Bye For Now',
 'BRB': 'Be Right Back',
 'BRT': 'Be Right There',
 'BTW': 'By The Way',
 'B4': 'Before',
 'CU': 'See You',
 'CUL8R': 'See You Later',
 'CYA': 'See You',
 'FAQ': 'Frequently Asked Questions',
 'FC': 'Fingers Crossed',
 'FWIW': "For What It's Worth",
 'FYI': 'For Your Information',
 'GAL': 'Get A Life',
 'GG': 'Good Game',
 'GN': 'Good Night',
 'GMTA': 'Great Minds Think Alike',
 'GR8': 'Great!',
 'G9': 'Genius',
 'IC': 'I See',
 'ICQ': 'I Seek you (also a chat program)',
 'ILU': 'ILU: I Love You',
 'IMHO': 'In My Honest/Humble Opinion',
 'IMO': 'In My Opinion',
 'IOW': 'In Other Words',
 'IRL': 'In Real Life',
 'KISS': 'Keep It Simple, Stupid',
 'LDR': 'Long Distance Relationship',
 'LM

In [81]:
#chat words treatment short form words like rofl lol gn etc
def chat_conv(text):
  new_text=[]
  for w in text.split():
    if w.upper() in chat_words_dict:
      new_text.append(chat_words_dict[w.upper()])
    else:
      new_text.append(w)
  return " ".join(new_text)

In [82]:
chat_conv('lol what! really you steeped on poop')

'Laughing Out Loud what! really you steeped on poop'

In [83]:
limited_data['overview']=limited_data['overview'].apply(chat_conv)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


**Spelling Correction**

In [84]:
# spelling correction

In [85]:
from textblob import TextBlob

In [86]:
incorrect_text="certain conditionas during several ggenerations aare moodified in the saame process"

In [90]:
textblb=TextBlob(incorrect_text)
textblb.correct().string

'certain conditions during several generations are modified in the same process'

In [91]:
limited_data['overview']=limited_data['overview'].apply(lambda tweet : TextBlob(tweet).correct().string)  #time taking

KeyboardInterrupt: ignored

In [92]:
limited_data['overview'][0]

'Yeondu asks her best friend Bora to collect all the information she can about Baek Hyunjin while she is away in the US for heart surgery Bora decides to get close to Baeks best friend Pung Woonho first However Boras clumsy plan unfolds in an unexpected direction In 1999 a year before the new century Bora who turns seventeen falls into the fever of first love'

In [93]:
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


**Remove Stop words**

In [94]:
#Removing Stop words
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [95]:
def remove_stopwords(text):
  new_text=[]

  for words in text.split():
    if words in stopwords.words('english'):
      new_text.append(' ')
    else:
      new_text.append(words)
  x=new_text[:]
  new_text.clear()
  return " ".join(x)

In [96]:
remove_stopwords("probably my all time favourite movie, a story of  selflessness, sacrifice abd dedication to a noble cause ")

'probably     time favourite movie,   story   selflessness, sacrifice abd dedication     noble cause'

In [97]:
limited_data['overview']=limited_data['overview'].apply(remove_stopwords)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [98]:
limited_data['overview'][0]

'Yeondu asks   best friend Bora   collect     information       Baek Hyunjin       away     US   heart surgery Bora decides   get close   Baeks best friend Pung Woonho first However Boras clumsy plan unfolds     unexpected direction In 1999   year     new century Bora   turns seventeen falls     fever   first love'

**Handling emoji**

In [99]:
#handling Emojis
#either remove or use library to transform it to other type
!pip install emoji
import emoji
print(emoji.demojize("this is 😀" ))

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
this is :grinning_face:


In [100]:
print(emoji.demojize("this is 😀😅" ))

this is :grinning_face::grinning_face_with_sweat:


In [101]:
def remove_emoji(string):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', string)

In [102]:
remove_emoji("this is a 😅")

'this is a '

**Tokenization**

In [103]:
#tokenization
#1using split

In [104]:
limited_data['overview'][0].split()

['Yeondu',
 'asks',
 'best',
 'friend',
 'Bora',
 'collect',
 'information',
 'Baek',
 'Hyunjin',
 'away',
 'US',
 'heart',
 'surgery',
 'Bora',
 'decides',
 'get',
 'close',
 'Baeks',
 'best',
 'friend',
 'Pung',
 'Woonho',
 'first',
 'However',
 'Boras',
 'clumsy',
 'plan',
 'unfolds',
 'unexpected',
 'direction',
 'In',
 '1999',
 'year',
 'new',
 'century',
 'Bora',
 'turns',
 'seventeen',
 'falls',
 'fever',
 'first',
 'love']

In [105]:
#2 using regular expression
text=" i am going delhi"
re.findall("[\w']+",text)

['i', 'am', 'going', 'delhi']

In [106]:
#3 NLTK METHOD
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize,sent_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [107]:
word_tokenize(text)

['i', 'am', 'going', 'delhi']

In [108]:
sent_tokenize("i live in delhi. i live in kolkata. i like uttrakhand.")

['i live in delhi.', 'i live in kolkata.', 'i like uttrakhand.']

In [109]:
#problem with nltk
word_tokenize("my email id is deepak.sdksakdjsak@gmail.com")

['my', 'email', 'id', 'is', 'deepak.sdksakdjsak', '@', 'gmail.com']

In [110]:
word_tokenize("i spent $5 last week")    # 5$ need to be together

['i', 'spent', '$', '5', 'last', 'week']

In [111]:
#4 spacy
!pip install spacy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [112]:
import spacy
tok=spacy.load("en_core_web_sm")

In [113]:
doc = tok("You only live once, but if you do it right, once is enough.")
for token in doc:
    print(token.text)

You
only
live
once
,
but
if
you
do
it
right
,
once
is
enough
.


In [114]:
doc = tok("i spent 5$ last week. i completed my ph.d last month. my gmail id is sa@gmail.com .")
for token in doc:
    print(token.text)

i
spent
5
$
last
week
.
i
completed
my
ph.d
last
month
.
my
gmail
i
d
is
sa@gmail.com
.


**Stemming** is the process of reducing a word to its word stem that affixes to suffixes and prefixes or to the roots of words known as a lemma. Stemming is important in natural language understanding (NLU) and natural language processing (NLP).

In [115]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
def stem_words(text):
  return" ".join([ps.stem(word) for word in text.split()])


In [116]:
sample="i have been running for a while"
stem_words(sample)

'i have been run for a while'

In [117]:
ps.stem("run")

'run'

In [118]:
ps.stem("sleeping")

'sleep'

In [119]:
ps.stem("swimming")

'swim'

In [120]:
ps.stem("movie")#sometime it stem words which not needed

'movi'

**Lemmatization**What is Lemmatization in NLP? Lemmatization is a text normalization technique used in Natural Language Processing (NLP), that switches any kind of a word to its base root mode. Lemmatization is responsible for grouping different inflected forms of words into the root form, having the same meaning.





In [121]:
#lemma (dict based comparision) slow compare to spacy (algo based)

In [122]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
word_net_lemma=WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


In [123]:
word_net_lemma.lemmatize("running",pos='v')

'run'

In [124]:
word_net_lemma.lemmatize("swimming",pos='v')

'swim'

In [125]:
word_net_lemma.lemmatize("movie",pos='v')

'movie'

In [126]:
#lemma used to show user
#spacy fast if not needed to show data to user

**Text Representation**

The first question arises is what is Feature Extraction from the text?  Feature Extraction is a general term that is also known as a text representation of text vectorization which is a process of converting text into numbers. we call vectorization because when text is converted in numbers it is in vector form.

**word embedding** is a term used for the representation of words for text analysis, typically in the form of a real-valued vector that encodes the meaning of the word such that the words that are closer in the vector space are expected to be similar in meaning.
Techniques for Feature Extraction

**frequency based**                   
* One-Hot Encoding                    
* Bag Of Words
* N grams
* TF IDF
* Glove

 **prediction based**

* Word2Vec (Deep learning)



**basic words**

Corpus(C) ~ The total number of combinations of words in the whole dataset is known as Corpus. In simple words concatenating all the text records of the dataset forms a corpus.

Vocabulary(V) ~ a total number of distinct words which form your corpus is known as Vocabulary.

Document(D) ~ There are multiple records in a dataset so a single record or review is referred to as a document.

Word(W) ~ Words that are used in a document are known as Word.

In [245]:
#onehot encoding
import numpy as np
import pandas as pd
sentences = ['nlp is a must topic', 'nlp is a boring topic', 'nlp nlp nlp file available for all']
df = pd.DataFrame({"text":sentences, "output":[1,1,0]})

In [246]:
df

text  output
0                 nlp is a must topic       1
1               nlp is a boring topic       1
2  nlp nlp nlp file available for all       0

In [247]:
token=df['text']
token_list=[]
for sent in token:
  for word in sent.split(' '):
      if word in token_list:
        pass
      else:
        token_list.append(word)


In [248]:
token_list

['nlp',
 'is',
 'a',
 'must',
 'topic',
 'boring',
 'file',
 'available',
 'for',
 'all']

In [249]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
integer_label_encoded = label_encoder.fit_transform(token_list)
label_encoded = integer_label_encoded.reshape(len(integer_label_encoded), 1)
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(label_encoded)
print(onehot_encoded)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Disadvantage of onehot encoding**

1) Sparsity – You can see that only a single sentence creates a vector of n*m size where n is the length of sentence m is a number of unique words in a document and 80 percent of values in a vector is zero.

2) No fixed Size – Each document is of a different length which creates vectors of different sizes and cannot feed to the model.

3) Does not capture semantics – The core idea is we have to convert text into numbers by keeping in mind that the actual meaning of a sentence should be observed in numbers that are not seen in one-hot encoding.

**Bag of words**

Bag of words is a little bit similar to one-hot encoding where we enter each word as a binary value and in a Bag of words we keep a single row and entry the count of words in a document. So we create a vocabulary and for a single document, we enter one entry of which words occur how many times in a document. Let us get to IDE and implement Bag-of words model using the Count vectorized class of sciket-learn.

In [267]:

from sklearn.feature_extraction.text import CountVectorizer

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words=stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [268]:
cv_=CountVectorizer(max_features=10,stop_words=stop_words)

In [269]:
x_data=cv_.fit_transform(df['text']).toarray()

In [270]:
pd.DataFrame(x_data)

0  1  2  3  4  5
0  0  0  0  1  1  1
1  0  1  0  0  1  1
2  1  0  1  0  3  0

In [277]:
cv_.vocabulary_

{'nlp': 4, 'must': 3, 'topic': 5, 'boring': 1, 'file': 2, 'available': 0}


Advantages

1) Simple and intuitive – Only a few lines of code are required to implement the technique.

2) Fix size vector – The problem which we saw in one-hot encoding where we are unable to feed data the data to machine learning model because each sentence forms a different size vector but here It ignores the new words and takes only words which are vocabulary so creates a vector of fix size.

Disadvantages

1) Out of vocabulary situation – It keeps count of vocabulary words so if new words come in a sentence it simply ignores it and tracks the count of the words that are in vocabulary. But what if the words it ignores are important in predicting the outcome so this is a disadvantage, only benefit is it does not throw an error.

2) Sparsity – when we have a large vocabulary, and the document contains a few repeated terms then it creates a sparse array.

3) Not considering ordering is an issue – It is difficult to estimate the semantics of the document.

**N-Grams**

The technique is similar to Bag of words. All the techniques till now we have read it is made up of a single word and we are not able to use them or utilize them for better understanding. So N-Gram technique solves this problem and constructs vocabulary with multiple words. When we built an N-gram technique we need to define like we want bigram, trigram, etc. So when you define N-gram and if it is not possible then it will throw an error. In our case, we cannot build after a 4 or 5-gram model. Let us try bigram and observe the outputs.

In [271]:

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=10,stop_words=stop_words,ngram_range=(2,5))

In [272]:
cv

CountVectorizer(max_features=10, ngram_range=(2, 5),
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...])

In [273]:
x_data_=cv.fit_transform(df['text']).toarray()

In [274]:
pd.DataFrame(x_data_)

0  1  2  3  4  5  6  7  8  9
0  0  0  1  0  0  0  0  1  1  0
1  1  0  0  1  1  0  0  0  0  0
2  0  1  0  0  0  1  1  0  0  2

In [275]:
cv.vocabulary_

{'nlp must': 7,
 'must topic': 2,
 'nlp must topic': 8,
 'nlp boring': 3,
 'boring topic': 0,
 'nlp boring topic': 4,
 'nlp nlp': 9,
 'nlp file': 5,
 'file available': 1,
 'nlp file available': 6}

Advantages

1) Able to capture semantic meaning of the sentence – As we use Bigram or trigram then it takes a sequence of sentences which makes it easy for finding the word relationship.

2) Intuitive and easy to implement – implementation of N-Gram is straightforward with a little bit of modification in Bag of words.

Disadvantages

1) As we move from unigram to N-Gram then dimension of vector formation or vocabulary increases due to which it takes a little bit more time in computation and prediction

2) no solution for out of vocabulary terms – we do not have a way another than ignoring the new words in a new sentence.

**TF-IDF **
This technique gives different values(weightage) to each word in a document. The core idea of assigning weightage is the word that appears multiple time in a document but has a rare appearance in corpus then it is very important for that document so it gives more weightage to that word. This weightage is calculated by two terms known as TF and IDF. So for finding the weightage of any word we find TF and IDF and multiply both the terms.

Term Frequency(TF) – The number of occurrences of a word in a document divided by a total number of terms in a document is referred to as Term Frequency. For example, I have to find the Term frequency of people in the below sentence then it will be 1/5. It says how frequently a particular word occurs in a particular document.

Inverse Document Frequency – Total number of documents in corpus divided by the total number of documents with term T in them and taking the log of a complete fraction is inverse document frequency. If we have a word that comes in all documents then the resultant output of the log is zero But in implementation sklearn uses a little bit different implementation because if it becomes zero then the contribution of the word is ignored so they add one in the resultant and because of which you can observe the values of TFIDF a bit high. If a word comes only a single time then IDF will be higher.

In [278]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.4804584 , 0.63174505, 0.37311881, 0.4804584 ],
       [0.        , 0.        , 0.63174505, 0.        , 0.        ,
        0.4804584 , 0.        , 0.37311881, 0.4804584 ],
       [0.3742551 , 0.3742551 , 0.        , 0.3742551 , 0.3742551 ,
        0.        , 0.        , 0.66312327, 0.        ]])

In [280]:
print(tfidf.get_feature_names_out())

['all' 'available' 'boring' 'file' 'for' 'is' 'must' 'nlp' 'topic']


In [281]:
print(tfidf.idf_)

[1.69314718 1.69314718 1.69314718 1.69314718 1.69314718 1.28768207
 1.69314718 1.         1.28768207]


Advantages:
- Easy to compute
- You have some basic metric to extract the most descriptive terms in a document
- You can easily compute the similarity between 2 documents using it

Disadvantages:
- TF-IDF is based on the bag-of-words (BoW) model, therefore it does not capture position in text, semantics, co-occurrences in different documents, etc.
- For this reason, TF-IDF is only useful as a lexical level feature
- Cannot capture semantics (e.g. as compared to topic models, word embeddings)

So it depends a lot for what you want to use TF-IDF.


**Word2Vec**

It is a two-layer neural network that processes the text by vectorizing words. Input for Word2Vec is a corpus, and the output is a set of feature vectors representing the words in that corpus. Embeddings generated by Word2Vec have proven to be successful on a variety of NLP tasks.

Word2Vec model has two methods for learning representations of words:

Continuous Bag-of-Words Model (CBOW): which predicts the middle word based on surrounding context words. The context consists of a few words before and after the current (middle) word. This architecture is called a bag-of-words model as the order of words in the context is not essential.

Continuous Skip-gram Model: It predicts words within a certain range before and after the current word in the same sentence.

In [1]:
import numpy as np
import pandas as pd
!pip install gensim

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


**Similair words training on game of throne story**

In [2]:

import gensim
import os

In [3]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [20]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []
for filename in os.listdir():
    if filename.endswith('.txt'):
        f = open(filename,'r+',encoding= 'unicode_escape')
        corpus = f.read()
        raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
      story.append(simple_preprocess(sent))

    

In [21]:
len(story)

200292

In [22]:
len(story[0])

372

In [23]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words=stopwords.words('english')
for i in range(len(story)):
  for words in story[i]:
    if words in stop_words:
      story[i].remove(words)
len(story)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


200292

In [19]:
len(story[0])

273

In [24]:
story

[['george',
  'martin',
  'dance',
  'dragons',
  'book',
  'five',
  'song',
  'ice',
  'fire',
  'dedication',
  'one',
  'fans',
  'lodey',
  'trebla',
  'stego',
  'pod',
  'caress',
  'yags',
  'ray',
  'mr',
  'kate',
  'chataya',
  'mormont',
  'mich',
  'jamie',
  'vanessa',
  'ro',
  'stubby',
  'louise',
  'agravaine',
  'wert',
  'malt',
  'jo',
  'mouse',
  'telisiane',
  'blackfyre',
  'bronn',
  'stone',
  'coyote',
  'daughter',
  'rest',
  'madmen',
  'wild',
  'women',
  'brotherhood',
  'without',
  'banners',
  'my',
  'website',
  'wizards',
  'elio',
  'linda',
  'lords',
  'westeros',
  'winter',
  'fabio',
  'wic',
  'gibbs',
  'dragonstone',
  'started',
  'men',
  'women',
  'asshai',
  'spain',
  'sang',
  'us',
  'bear',
  'maiden',
  'fair',
  'fabulous',
  'fans',
  'italy',
  'gave',
  'so',
  'much',
  'wine',
  'my',
  'readers',
  'finland',
  'germany',
  'brazil',
  'portugal',
  'france',
  'netherlands',
  'all',
  'distant',
  'lands',
  'you',
  '

In [25]:
model=gensim.models.Word2Vec(window=10,min_count=2)


In [26]:
model.build_vocab(story)

In [27]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(7737783, 8407040)

In [32]:
model.wv.most_similar('queen')

[('margaery', 0.6218781471252441),
 ('khaleesi', 0.6054679155349731),
 ('grace', 0.5870234370231628),
 ('stormborn', 0.5834082961082458),
 ('khal', 0.5808515548706055),
 ('princess', 0.5764899849891663),
 ('hizdahr', 0.576461672782898),
 ('court', 0.5714207887649536),
 ('myrcella', 0.5704178810119629),
 ('arianne', 0.5669552683830261)]

In [33]:
model.wv.most_similar('daenerys')

[('targaryen', 0.712793231010437),
 ('stormborn', 0.6928570866584778),
 ('myrcella', 0.6351075172424316),
 ('viserys', 0.6309526562690735),
 ('interfered', 0.6133289337158203),
 ('quicken', 0.6017268300056458),
 ('khaleesi', 0.59186851978302),
 ('westeros', 0.580097496509552),
 ('cersei', 0.579410195350647),
 ('unburnt', 0.5732007026672363)]

In [34]:
model.wv.doesnt_match(['cersei','jaime','bronn','tyrion'])

/usr/local/lib/python3.7/dist-packages/gensim/models/keyedvectors.py:895: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  vectors = vstack(self.word_vec(word, use_norm=True) for word in used_words).astype(REAL)


'bronn'

In [35]:
model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

'jon'

In [36]:
model.wv.similarity('arya','sansa')

0.82238054

In [37]:
model.wv.similarity('cersei','sansa')

0.69136643

In [38]:
model.wv.similarity('tywin','sansa')

0.28374442

In [57]:
len(model.wv.index2word)
y=model.wv.index2word

In [52]:
len(model.wv.vectors)

18917

In [54]:
from sklearn.decomposition import PCA
pca=PCA(n_components=3)
x=pca.fit_transform(model.wv.vectors)



In [56]:
x.shape

(18917, 3)

In [59]:
#representation of top 100 words
import plotly.express as px
fig=px.scatter_3d(x[:100],x=0,y=1,z=2,color=y[:100])
fig.show()